### ISSUE TITLE
Error on clicking close in Reinforcement TaskPanel dialogs

### ISSUE THREAD

**Issue by SurajDadral** [amrit3701/FreeCAD-Reinforcement#111]
<class 'TypeError'>: function takes exactly 0 arguments (1 given)
18:28:10  Traceback (most recent call last):
  File "/home/blank/.FreeCAD/Mod/Reinforcement/StraightRebar.py", line 280, in accept
    FreeCADGui.Control.closeDialog(self)
<class 'TypeError'>: function takes exactly 0 arguments (1 given)

FreeCAD info:
OS: Kali GNU/Linux Rolling (GNOME/gnome)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.22665 (Git) AppImage
Build type: Release
Branch: master
Hash: b0d7850406e046f3b7a8cd5da261e7d54df6bd99
Python version: 3.8.6
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.4.0
Locale: English/India (en_IN)

**Comment by Sudhanshu-Dubey14** [comment]
Let me give it a try.

**Comment by Sudhanshu-Dubey14** [comment]
I can't reproduce the error on my version of FreeCAD:

OS: Arch Linux (XFCE/xfce)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.22609 +8 (Git)
Build type: Release
Branch: femexamples
Hash: 6a8a89cb65aa49b8ac4883e7f5e5b6c205cd9a60
Python version: 3.8.5
Qt version: 5.15.1
Coin version: 4.0.0
OCC version: 7.4.0
Locale: English/India (en_IN)

I will get the latest version of FreeCAD and try to reproduce the error.

**Comment by Sudhanshu-Dubey14** [comment]
Bug confirmed in the following FreeCAD version:

OS: Arch Linux (XFCE/xfce)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.22759 (Git)
Build type: Release
Branch: master
Hash: f3bdaaa55a6c03b297924c40819d23e4603fa55b
Python version: 3.8.6
Qt version: 5.15.1
Coin version: 4.0.1
OCC version: 7.4.0
Locale: English/India (en_IN)

I suppose the issue because of a change FreeCAD master with [this commit](https://github.com/FreeCAD/FreeCAD/commit/7db21217f42a62246d2c841c9d03e0bbd9b68b77#diff-eabf59eed1f3c38bcad7b03e9b960fb387462900b6bb9147414eba32f1ec66b8). So removing `self` as an argument should resolve the issue. I will try that and make a PR.
